export const projects = [
	  {
    title: "MedGS: Gaussian Splatting for 3D Medical Imaging",
    description:
      "Semi-supervised neural implicit surface reconstruction framework for medical volumetric data. Combines Gaussian Splatting with multi-modal interpolation.",
    stack: "Python, PyTorch, NumPy, 3D Visualization",
    time: "2025",
    repo: "https://github.com/gmum/MedGS",
    link: "https://arxiv.org/abs/2509.16806"
    },
  {
    title: "PlakietkUJ – Template Designer for Room Signage",
    description:
        "A Windows desktop application built with C# and WPF (.NET 7) for designing and printing customizable templates for room signage. Features include background editing, image/text elements, JSON-based save/load, and bilingual (PL/EN) UI.",
    stack: "C#, WPF, .NET 7, JSON, Windows",
    time: "2024",
    repo: "https://github.com/ikolton/PlakietkUJ"
    },
    {
    title: "Invoice OCR Scanner",
    description:
        "A Python-based tool that combines classic image processing with modern OCR models to extract structured data from invoices. It performs preprocessing steps such as denoising, contrast enhancement, deskewing, and cropping, then integrates existing ML models (Tesseract, EasyOCR) for text recognition and field extraction. Includes a Streamlit web interface for easy testing and visualization.",
    stack: "Python, OpenCV, NumPy, Tesseract OCR, EasyOCR, Streamlit",
    time: "2024",
    repo: "https://github.com/ikolton/OCR"
    },
{
  title: "ML Prototypes Feedback Collector",
  description:
    "This project is designed to create a tool for interactive user participation in the interpretation of results generated by machine learning systems, with a particular focus on visual classification. The aim is to enable users to verify and provide feedback on the accuracy of object identification and classification in images by the machine learning model.",
  stack: "Web, User Feedback, Classification, UI/UX, Data Collection",
  time: "2024",
  repo: "https://github.com/millamy/ml-prototypes-feedback-collector"
}


];